### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by andriisoldatenko**
More details at elbuo8/sendgrid-django/issues/36

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@elbuo8 Works! Thanks! will fix :)

**Comment by andriisoldatenko** [comment]
@elbuo8 Please review.

**Comment by andriisoldatenko** [comment]
@elbuo8 Please review.
I think we can merge now, and later add more tests

**Comment by andriisoldatenko** [comment]
@vananabu Please review.

**Comment by elbuo8** [comment]
LGTM

**Pull request merged**
