### PR TITLE
Add support for List-Unsubscribe header

### PR DESCRIPTION
**Pull request by jonklo**
More info: http://www.list-unsubscribe.com/

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@elbuo8 Looks like useful feature.
What do you think?

**Comment by andriisoldatenko** [comment]
@jonklo You should rebase from master.

**Comment by elbuo8** [comment]
👍 

Please rebase.

**Comment by jonklo** [comment]
I changed it to support arbitrary headers from the email object, could be useful for different use cases. 

Depends on [sendgrid >= 3.5](https://github.com/sendgrid/sendgrid-python/blob/master/CHANGELOG.md#350---2016-10-11), what do you think about upping the required dependency?

**Comment by andriisoldatenko** [comment]
I think it should works, please take a look https://github.com/elbuo8/sendgrid-django/blob/master/setup.py#L17

**Comment by elbuo8** [comment]
@jonklo please make the changes to `setup.py` to ensure the right dependency is installed. After that we can make it a major bump.

**Comment by andriisoldatenko** [comment]
LGTM

**Pull request merged**
