### PR TITLE
Properly handle the `reply_to` header value

### PR DESCRIPTION
**Pull request by MickaelBergem**
See #34 and #50 for the details.

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@MickaelBergem Thanks for creating patch. Can you please add unit tests?

**Comment by kevin-brown** [comment]
So, the `Reply-To` header supports setting multiple addresses, and Django handles this by making `reply_to` a tuple. SendGrid actually supports multiple `Reply-To` addresses as well if you set the header.

http://stackoverflow.com/q/15820418/359284

Unfortunately it looks like the web API does not handle multiple `Reply-To` addresses.

**Comment by vinitkumar** [comment]
@MickaelBergem does your patch work?

**Comment by jancsarc** [comment]
It isn't working for me so far...

**Comment by MickaelBergem** [comment]
@vinitkumar @jancsarc sorry guys I lacked time on this and never provided the unit tests, and gave up using my fork, don't remember if I was able to use it successfully.

Feel free to test / post the error you are getting here / take over the fixing of this bug :)

**Pull request closed without merging**
